pipeline:
  name: Build harness
  identifier: Build_mrrmore_harness_1782321962737
  projectIdentifier: Harness_Learning
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Python
                    command: print('Hello')
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1782151092878
        repoName: mrrmore/harness
        build: <+input>
